version: "3.6"
services:
  grafana:
    image: jberny/katacoda-promql-grafana:latest
    ports:
      - "3000:3000"
    networks:
      - promql-net
    volumes:
      - ${PROMQLWD}/assets/grafana:/etc/grafana
  prometheus:
    image: prom/prometheus:v2.25.0
    ports:
      - "9090:9090"
    networks:
      - promql-net
    volumes:
      - ${PROMQLWD}/assets/prometheus:/etc/prometheus
  mondemoapi:
    image: jberny/mondemoapi:v0.0.6
    ports:
      - "8080:8080"
    networks:
      - promql-net

networks:
  promql-net:
