name: build-monitoring-demo-api
on: [push]
jobs:
  build-monitoring-demo-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
      - run: build.sh
           working-directory: monitoring-demo-api